### ISSUE TITLE
Questions on function saveGraphFile

### ISSUE THREAD

**Issue by YanhaoZhang** [MinaHenein/do-slam#2]
Hi Mina
Thank you so much that you open sourced your code. I am trying to run **RSS18ExpB2** which I guess is the second simulation in your paper. However I got an error saying "_External converter methods for package-qualified classes not supported._" as follow:
![image](https://user-images.githubusercontent.com/36495922/45731405-cbd97d80-bc1a-11e8-9115-e1eeed517553.png)

I made a little change in class _Graph_ as follow
![image](https://user-images.githubusercontent.com/36495922/45731584-a8630280-bc1b-11e8-8863-00389123e7a1.png)

However I got another error as follow:
![image](https://user-images.githubusercontent.com/36495922/45731641-f24be880-bc1b-11e8-9123-9ffa3003c703.png)

I guess the reason is there are three inputs of _saveGraphFile_. May I ask you how to solve this?

Thank you so much :) 

Cheers,
Yanhao Zhang

**Comment by MinaHenein** [comment]
Hi Yanhao,

Thanks for using my code and for shouting out this error,

if you add those couple of lines (the ones between the %%%%%%%%%%) to the main; it should work fine

config.set('pointMotionMeasurement','point2DataAssociation');
config.set('SE3MotionVertexInitialization','translation')
config.set('newMotionVertexPerNLandmarks',inf)
config.set('measurementsFileName','RSS18ExpB2_measurements.graph');
config.set('groundTruthFileName','RSS18ExpB2_groundTruth.graph');
sensor.generateMeasurements(config);
writeDataAssociationVerticesEdges_constantSE3Motion(config,constantSE3ObjectMotion);
% added lines
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
config.set('measurementsFileName','RSS18ExpB2_measurementsTest.graph');
config.set('groundTruthFileName','RSS18ExpB2_groundTruthTest.graph');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
measurementsCell = graphFileToCell(config,config.measurementsFileName);
groundTruthCell  = graphFileToCell(config,config.groundTruthFileName);

Please don't forget to cite our paper in any work you publish,


@article{henein2018simultaneous,
  title={Simultaneous Localization and Mapping with Dynamic Rigid Objects},
  author={Henein, Mina and Kennedy, Gerard and Ila, Viorela and Mahony, Robert},
  journal={arXiv preprint arXiv:1805.03800},
  year={2018}
}


And wait for a more complete version of this work to be published soon,

Best regards,
Mina Henein
________________________________

**Comment by YanhaoZhang** [comment]
Hi Mina
Thank you so much for your reply! I will have a try. Your code is so helpful. Can't wait for the final version haha. Probably I may ask you some more questions, but I won't bother you too much.

I won't forget to cite your paper. Good luck on your publication. :+1:  

Cheers,
Yanhao Zhang
